const { SensorReading, IoTAlert, GarbageArea, Report } = require("../models");
const { getIO } = require("../config/socket");
const { barangayFilter } = require("../middleware/barangayScope");
const { classifyAirQuality, generateIoTAlerts, IOT_THRESHOLDS } = require("../services/iotService");
const { addBarangayScore } = require("../services/gamificationService");

// Memory caches for alert throttling
const sensorAlertCooldowns = new Map();
const recentReportHashes = new Map();

// POST /api/iot/sensor-data
exports.ingestSensorData = async (req, res, next) => {
  const {
    sensorId,
    deviceType,
    location,
    barangay,
    rawValue,
    airQuality: clientAirQuality,
    cleanThreshold,
    criticalThreshold,
    measurementType,
    isOfficialAQI,
    ammonia,
    methane,
    hydrogen,
    co2,
    temperature,
    humidity,
    binLevel,
    calibratedValue,
  } = req.body;

  if (!sensorId) {
    return res.status(400).json({ error: "sensorId is required" });
  }

  try {
    const rawValNum = rawValue != null ? Number(rawValue) : 0;
    const cleanThreshNum = cleanThreshold != null ? Number(cleanThreshold) : 200;
    const critThreshNum = criticalThreshold != null ? Number(criticalThreshold) : 400;

    let airQuality = "CLEAN";
    if (clientAirQuality && ["CLEAN", "MODERATE", "CRITICAL", "Clean", "Moderate", "Critical"].includes(clientAirQuality)) {
      airQuality = clientAirQuality.toUpperCase();
    } else {
      airQuality = classifyAirQuality(rawValNum, cleanThreshNum, critThreshNum);
    }

    const reading = await SensorReading.create({
      sensorId,
      deviceType: deviceType || "ESP32",
      location: location || "",
      barangay: barangay || "",
      rawValue: rawValNum,
      cleanThreshold: cleanThreshNum,
      criticalThreshold: critThreshNum,
      measurementType: measurementType || "MQ-135 garbage-area air-quality classification",
      isOfficialAQI: isOfficialAQI === true,
      airQuality,
      ammonia: ammonia != null ? Number(ammonia) : 0,
      methane: methane != null ? Number(methane) : 0,
      hydrogen: hydrogen != null ? Number(hydrogen) : null,
      co2: co2 != null ? Number(co2) : null,
      temperature: temperature != null ? Number(temperature) : null,
      humidity: humidity != null ? Number(humidity) : null,
      binLevel: binLevel != null ? Number(binLevel) : null,
      calibratedValue: calibratedValue != null ? Number(calibratedValue) : null,
      timestamp: new Date(),
    });

    const candidateAlerts = generateIoTAlerts(reading);
    const savedAlerts = [];
    const now = Date.now();
    const ALERT_COOLDOWN_MS = 10 * 60 * 1000;

    for (const a of candidateAlerts) {
      const key = `${a.sensorId}_${a.severity}`;
      const lastSent = sensorAlertCooldowns.get(key) || 0;
      if (now - lastSent > ALERT_COOLDOWN_MS) {
        sensorAlertCooldowns.set(key, now);
        const doc = await IoTAlert.create({ ...a, readingId: reading._id });
        savedAlerts.push(doc);
        const io = getIO();
        if (io) io.emit("iot:alert", doc);
      }
    }

    let autoReport = null;
    const isHighHazard =
      airQuality === "CRITICAL" ||
      airQuality === "Critical" ||
      rawValNum >= critThreshNum;

    if (isHighHazard) {
      const reportKey = `${sensorId}_${location || "unknown"}`;
      const lastReport = recentReportHashes.get(reportKey) || 0;
      const REPORT_COOLDOWN_MS = 60 * 60 * 1000;

      if (now - lastReport > REPORT_COOLDOWN_MS) {
        recentReportHashes.set(reportKey, now);
        autoReport = await Report.create({
          title: `IoT Alert: Critical Air Quality at ${location || sensorId}`,
          description: `Automatic report generated by Sensor ${sensorId}. Air Quality: ${airQuality} (Raw ADC: ${rawValNum}, Critical Threshold: ${critThreshNum}).`,
          category: "Hazardous Waste",
          priority: "Critical",
          status: "pending",
          location: location || sensorId,
          barangay: barangay || "",
          reportedBy: `IoT Sensor (${sensorId})`,
          deadline: new Date(Date.now() + 24 * 60 * 60 * 1000),
          statusHistory: [
            {
              status: "pending",
              changedBy: "IoT System",
              changedAt: new Date(),
            },
          ],
        });
        const io = getIO();
        if (io) io.emit("report:new", autoReport);
      }
    }

    const isCrit =
      airQuality === "CRITICAL" ||
      airQuality === "Critical" ||
      rawValNum >= critThreshNum;
    const isMod =
      airQuality === "MODERATE" ||
      airQuality === "Moderate" ||
      (rawValNum >= cleanThreshNum && rawValNum < critThreshNum);

    const areaStatus = isCrit ? "critical" : isMod ? "moderate" : "clean";
    const areaIntensity = isCrit ? 0.9 : isMod ? 0.5 : 0.2;

    const updatedArea = await GarbageArea.findOneAndUpdate(
      { sensorId },
      {
        $set: {
          rawValue: rawValNum,
          airQuality: airQuality,
          lastReadingAt: new Date(),
          status: areaStatus,
          intensity: areaIntensity,
          isActive: true,
        },
        $setOnInsert: {
          name: location || sensorId,
          barangay: barangay || "",
          reportCount: 0,
          source: "iot",
        },
      },
      { upsert: true, new: true }
    );

    const io = getIO();
    if (io) {
      io.emit("garbage-area:updated", updatedArea);
      const iotColorMap = { critical: "red", moderate: "yellow", clean: "green" };
      io.emit("zone:status:update", {
        zoneId: updatedArea._id,
        areaId: updatedArea._id,
        name: updatedArea.name,
        barangay: updatedArea.barangay,
        previousStatus: null,
        newStatus: areaStatus,
        newColor: iotColorMap[areaStatus] || "yellow",
        rawValue: rawValNum,
        airQuality: airQuality,
        isActive: true,
        reason: "iot_sensor_reading",
        changedBy: `Sensor ${sensorId}`,
        timestamp: new Date().toISOString(),
      });
      io.emit("iot:reading", reading);
    }

    if (updatedArea.barangay) {
      const qualityPts =
        airQuality === "CLEAN" || airQuality === "Clean" || airQuality === "Good"
          ? 3
          : airQuality === "MODERATE" || airQuality === "Moderate"
          ? 1
          : airQuality === "CRITICAL" || airQuality === "Critical"
          ? -5
          : 0;
      if (qualityPts !== 0) {
        addBarangayScore(
          updatedArea.barangay,
          qualityPts,
          "iotScore",
          qualityPts > 0 ? "areaQualityPts" : undefined
        ).catch(() => {});
      }
    }

    res.status(201).json({
      status: "success",
      reading,
      airQuality,
      alerts: savedAlerts,
      autoReport: autoReport || null,
      thresholds: { clean: cleanThreshNum, critical: critThreshNum },
      area: updatedArea,
    });
  } catch (err) {
    next(err);
  }
};

// GET /api/iot/readings
exports.getReadings = async (req, res, next) => {
  try {
    const { sensorId, limit = 100, hours } = req.query;
    const filter = barangayFilter(req.official || req);
    if (sensorId) filter.sensorId = sensorId;
    if (hours) {
      filter.timestamp = { $gte: new Date(Date.now() - Number(hours) * 3600 * 1000) };
    }
    const readings = await SensorReading.find(filter).sort({ timestamp: -1 }).limit(Number(limit));
    res.json(readings);
  } catch (err) {
    next(err);
  }
};

// GET /api/iot/readings/latest
exports.getLatestReadings = async (req, res, next) => {
  try {
    const brgyFilter = barangayFilter(req.official || req);
    const matchStage = Object.keys(brgyFilter).length ? { $match: brgyFilter } : null;
    const pipeline = [
      ...(matchStage ? [matchStage] : []),
      { $sort: { timestamp: -1 } },
      { $group: { _id: "$sensorId", reading: { $first: "$$ROOT" } } },
      { $replaceRoot: { newRoot: "$reading" } },
      { $sort: { sensorId: 1 } },
    ];
    const latest = await SensorReading.aggregate(pipeline);

    const sensorIds = latest.map((r) => r.sensorId);
    const areas = await GarbageArea.find({ sensorId: { $in: sensorIds } });
    const areaMap = {};
    areas.forEach((a) => {
      areaMap[a.sensorId] = a;
    });

    const enriched = latest.map((r) => ({
      ...r,
      barangay: r.barangay || areaMap[r.sensorId]?.barangay || "",
      location: r.location || areaMap[r.sensorId]?.name || r.sensorId,
      garbageAreaId: areaMap[r.sensorId]?._id || null,
    }));

    res.json(enriched);
  } catch (err) {
    next(err);
  }
};

// GET /api/iot/trends
exports.getTrends = async (req, res, next) => {
  try {
    const { sensorId, hours = 168 } = req.query;
    const since = new Date(Date.now() - Number(hours) * 3600 * 1000);
    const match = {
      timestamp: { $gte: since },
      ...barangayFilter(req.official || req),
    };
    if (sensorId) match.sensorId = sensorId;

    const trends = await SensorReading.aggregate([
      { $match: match },
      {
        $group: {
          _id: {
            year: { $year: "$timestamp" },
            month: { $month: "$timestamp" },
            day: { $dayOfMonth: "$timestamp" },
            hour: { $hour: "$timestamp" },
          },
          avgRawValue: { $avg: "$rawValue" },
          avgAmmonia: { $avg: "$ammonia" },
          avgMethane: { $avg: "$methane" },
          avgTemperature: { $avg: "$temperature" },
          avgHumidity: { $avg: "$humidity" },
          avgBinLevel: { $avg: "$binLevel" },
          maxAmmonia: { $max: "$ammonia" },
          maxMethane: { $max: "$methane" },
          count: { $sum: 1 },
        },
      },
      { $sort: { "_id.year": 1, "_id.month": 1, "_id.day": 1, "_id.hour": 1 } },
    ]);

    const formatted = trends.map((t) => {
      const { year, month, day, hour } = t._id;
      const dateStr = `${month}/${day} ${String(hour).padStart(2, "0")}:00`;
      return {
        date: dateStr,
        rawValue: Math.round(t.avgRawValue || 0),
        ammonia: Math.round(t.avgAmmonia * 10) / 10,
        methane: Math.round(t.avgMethane * 100) / 100,
        temperature: Math.round(t.avgTemperature * 10) / 10,
        humidity: Math.round(t.avgHumidity * 10) / 10,
        binLevel: Math.round(t.avgBinLevel),
        maxAmmonia: t.maxAmmonia,
        maxMethane: t.maxMethane,
        samples: t.count,
      };
    });

    res.json(formatted);
  } catch (err) {
    next(err);
  }
};

// GET /api/iot/alerts
exports.getAlerts = async (req, res, next) => {
  try {
    const { limit = 50, severity, acknowledged } = req.query;
    const filter = barangayFilter(req.official || req);
    if (severity) filter.severity = severity;
    if (acknowledged !== undefined) filter.acknowledged = acknowledged === "true";

    const alerts = await IoTAlert.find(filter).sort({ createdAt: -1 }).limit(Number(limit));
    res.json(alerts);
  } catch (err) {
    next(err);
  }
};

// PATCH /api/iot/alerts/:id/acknowledge
exports.acknowledgeAlert = async (req, res, next) => {
  try {
    const alert = await IoTAlert.findByIdAndUpdate(req.params.id, { acknowledged: true }, { new: true });
    if (!alert) return res.status(404).json({ error: "Alert not found" });

    const io = getIO();
    if (io) io.emit("iot:alert:acknowledged", alert);
    res.json(alert);
  } catch (err) {
    next(err);
  }
};

// DELETE /api/iot/alerts
exports.clearAlerts = async (req, res, next) => {
  try {
    const filter = barangayFilter(req.official || req);
    const result = await IoTAlert.deleteMany(filter);
    const io = getIO();
    if (io) io.emit("iot:alerts:cleared");
    res.json({ success: true, deletedCount: result.deletedCount });
  } catch (err) {
    next(err);
  }
};

// DELETE /api/iot/alerts/:id
exports.deleteAlert = async (req, res, next) => {
  try {
    const alert = await IoTAlert.findByIdAndDelete(req.params.id);
    if (!alert) return res.status(404).json({ error: "Alert not found" });

    const io = getIO();
    if (io) io.emit("iot:alert:deleted", { id: req.params.id });
    res.json({ success: true });
  } catch (err) {
    next(err);
  }
};

// GET /api/iot/health-summary
exports.getHealthSummary = async (req, res, next) => {
  try {
    const latest = await SensorReading.aggregate([
      { $sort: { timestamp: -1 } },
      { $group: { _id: "$sensorId", doc: { $first: "$$ROOT" } } },
      { $replaceRoot: { newRoot: "$doc" } },
    ]);

    const high = latest.filter((r) => (r.rawValue || 0) >= (r.criticalThreshold || 400) || r.airQuality === "CRITICAL" || r.airQuality === "Critical");
    const moderate = latest.filter(
      (r) =>
        !high.some((h) => h._id?.toString() === r._id?.toString()) &&
        ((r.rawValue || 0) >= (r.cleanThreshold || 200) || r.airQuality === "MODERATE" || r.airQuality === "Moderate")
    );
    const low = latest.filter((r) => (r.rawValue || 0) < (r.cleanThreshold || 200));

    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const recentAlerts = await IoTAlert.find({ createdAt: { $gte: sevenDaysAgo } })
      .sort({ createdAt: -1 })
      .limit(10);

    const barangayMap = {};
    latest.forEach((r) => {
      if (r.barangay) {
        if (!barangayMap[r.barangay]) barangayMap[r.barangay] = { name: r.barangay, sensors: [] };
        barangayMap[r.barangay].sensors.push(r);
      }
    });

    const barangaysAtRisk = Object.values(barangayMap)
      .filter((b) => b.sensors.some((s) => (s.rawValue || 0) >= (s.cleanThreshold || 200) || s.airQuality === "MODERATE" || s.airQuality === "CRITICAL"))
      .map((b) => ({
        name: b.name,
        maxRawValue: Math.max(...b.sensors.map((s) => s.rawValue || 0)),
        sensorCount: b.sensors.length,
      }))
      .sort((a, b) => b.maxRawValue - a.maxRawValue)
      .slice(0, 5);

    res.json({
      riskCounts: { high: high.length, moderate: moderate.length, low: low.length },
      recentAlerts,
      barangaysAtRisk,
    });
  } catch (err) {
    next(err);
  }
};

// GET /api/iot/summary
exports.getSummary = async (req, res, next) => {
  try {
    const oneHourAgo = new Date(Date.now() - 3600 * 1000);
    const brgyFilter = barangayFilter(req.official || req);
    const [totalSensors, recentReadings, activeAlerts, criticalAlerts] = await Promise.all([
      GarbageArea.distinct("sensorId", { sensorId: { $ne: null }, ...brgyFilter }),
      SensorReading.countDocuments({
        timestamp: { $gte: oneHourAgo },
        ...brgyFilter,
      }),
      IoTAlert.countDocuments({ acknowledged: false, ...brgyFilter }),
      IoTAlert.countDocuments({
        acknowledged: false,
        severity: "critical",
        ...brgyFilter,
      }),
    ]);
    res.json({
      totalSensors: totalSensors.length,
      recentReadings,
      activeAlerts,
      criticalAlerts,
    });
  } catch (err) {
    next(err);
  }
};
