import { useState, useEffect } from 'react';
import { MapContainer, TileLayer, Polygon, Marker, useMapEvents, useMap } from 'react-leaflet';
import axios from 'axios';
import { 
  ShieldCheck, MapPin, Save, RotateCcw, 
  Trash2, Layers, Info, Map as MapIcon,
  Search, CheckCircle, AlertCircle, Sparkles
} from 'lucide-react';
import API from '../../config';

const CEBU_CENTER = [10.3157, 123.8854];

function MapEvents({ onMapClick }) {
  useMapEvents({
    click: (e) => onMapClick(e.latlng),
  });
  return null;
}

function MapController({ center }) {
  const map = useMap();
  useEffect(() => {
    if (center) map.flyTo(center, 15);
  }, [center, map]);
  return null;
}

export default function JurisdictionManager() {
  const [barangays] = useState(["Lahug", "Apas", "Guadalupe", "Mabolo", "Talamban", "Banilad", "Mandaue"]);
  const [selectedBarangay, setSelectedBarangay] = useState("");
  const [points, setPoints] = useState([]);
  const [savedBoundaries, setSavedBoundaries] = useState({});
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [isSatellite, setIsSatellite] = useState(false);
  const [mapCenter, setMapCenter] = useState(CEBU_CENTER);
  const [generatingAI, setGeneratingAI] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState([]);
  const [searchLoading, setSearchLoading] = useState(false);
  const [barangaySearch, setBarangaySearch] = useState("");
  const [toast, setToast] = useState(null);

  const fetchBoundaries = async () => {
    setLoading(true);
    try {
      const { data } = await axios.get(`${API}/api/barangays/boundaries`);
      const boundaryMap = {};
      data.forEach(doc => {
        boundaryMap[doc.barangay] = doc.boundary;
      });
      setSavedBoundaries(boundaryMap);
    } catch (err) {
      console.error('Failed to fetch boundaries:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBoundaries();
  }, []);

  const handleMapClick = (latlng) => {
    if (!selectedBarangay) {
      showToast("Please select a barangay first", "error");
      return;
    }
    setPoints(prev => [...prev, [latlng.lat, latlng.lng]]);
  };

  const handleSave = async () => {
    if (!selectedBarangay) return;
    if (points.length < 3) {
      showToast("Draw a complete polygon with at least 3 points", "error");
      return;
    }

    setSaving(true);
    try {
      await axios.post(`${API}/api/barangays/boundary`, {
        barangay: selectedBarangay,
        boundary: points,
        color: '#3B82F6'
      });
      showToast(`${selectedBarangay} boundary saved successfully!`, "success");
      fetchBoundaries();
    } catch (err) {
      showToast("Failed to save boundary", "error");
    } finally {
      setSaving(false);
    }
  };

  const handleAIGenerate = async () => {
    if (!selectedBarangay) return;
    setGeneratingAI(true);
    try {
      const token = localStorage.getItem('admin_token');
      const { data } = await axios.post(`${API}/api/admin/generate-boundary`, 
        { barangay: selectedBarangay },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setPoints(data.boundary);
      setMapCenter(data.boundary[0]);
      showToast("Boundary generated by AI!", "success");
    } catch (err) {
      showToast(err.response?.data?.error || "AI generation failed", "error");
    } finally {
      setGeneratingAI(false);
    }
  };

  const clearCurrent = () => {
    setPoints([]);
  };

  const loadExisting = () => {
    if (savedBoundaries[selectedBarangay]) {
      setPoints(savedBoundaries[selectedBarangay]);
      setMapCenter(savedBoundaries[selectedBarangay][0]);
    } else {
      showToast("No saved boundary for this barangay", "info");
    }
  };

  const showToast = (msg, type) => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3000);
  };

  const handleSearch = async (query) => {
    setSearchQuery(query);
    if (!query || query.length < 3) {
      setSearchResults([]);
      return;
    }
    setSearchLoading(true);
    try {
      const { data } = await axios.get(`https://nominatim.openstreetmap.org/search`, {
        params: {
          q: `${query}, Cebu City`,
          format: 'json',
          limit: 5,
        }
      });
      setSearchResults(data);
    } catch (err) {
      console.error('Search failed:', err);
    } finally {
      setSearchLoading(false);
    }
  };

  const selectSearchResult = (result) => {
    const lat = parseFloat(result.lat);
    const lon = parseFloat(result.lon);
    setMapCenter([lat, lon]);
    setSearchResults([]);
    setSearchQuery(result.display_name);
  };

  return (
    <div className="flex h-[calc(100vh-8rem)] bg-white rounded-[40px] border border-slate-200 overflow-hidden shadow-2xl">
      {/* Sidebar Controls */}
      <div className="w-[380px] border-r border-slate-100 flex flex-col p-8 space-y-8 overflow-y-auto">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2.5 bg-emerald-50 rounded-2xl text-emerald-600 shadow-sm">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <h2 className="text-xl font-black text-slate-900 tracking-tight">Jurisdiction</h2>
          </div>
          <p className="text-sm text-slate-500 font-medium leading-relaxed">
            Define administrative boundaries to restrict route planning and fleet assignments.
          </p>
        </div>

        <div className="space-y-4">
          <div className="flex items-center justify-between ml-1">
            <label className="text-[11px] font-black text-slate-400 uppercase tracking-[0.2em]">
              Target Barangay
            </label>
            <div className="relative">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-slate-300" />
              <input 
                type="text"
                placeholder="Filter..."
                className="pl-7 pr-3 py-1.5 bg-slate-50 border border-slate-100 rounded-lg text-[10px] font-bold focus:outline-none focus:ring-1 focus:ring-emerald-500 w-28"
                value={barangaySearch}
                onChange={(e) => setBarangaySearch(e.target.value)}
              />
            </div>
          </div>
          <div className="grid grid-cols-1 gap-2 max-h-[300px] overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-slate-200">
            {barangays
              .filter(b => b.toLowerCase().includes(barangaySearch.toLowerCase()))
              .map(b => (
              <button
                key={b}
                onClick={() => {
                  setSelectedBarangay(b);
                  setPoints([]);
                }}
                className={`flex items-center justify-between px-5 py-3.5 rounded-2xl border-2 transition-all font-bold text-sm ${
                  selectedBarangay === b 
                  ? 'border-emerald-500 bg-emerald-50/50 text-emerald-700' 
                  : 'border-slate-50 hover:border-slate-200 text-slate-600'
                }`}
              >
                <div className="flex items-center gap-3">
                  <MapPin className={`w-4 h-4 ${selectedBarangay === b ? 'text-emerald-500' : 'text-slate-300'}`} />
                  {b}
                </div>
                {savedBoundaries[b] && (
                  <CheckCircle className="w-4 h-4 text-emerald-500" />
                )}
              </button>
            ))}
          </div>
        </div>

        {selectedBarangay && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="p-5 bg-slate-900 rounded-[32px] text-white space-y-4 shadow-xl">
              <div className="flex items-center gap-2 text-emerald-400 font-bold text-xs uppercase tracking-widest">
                <Info className="w-4 h-4" /> Drawing Mode Active
              </div>
              <p className="text-xs text-slate-400 leading-relaxed font-medium">
                Click on the map to place boundary vertices for <span className="text-white font-black">{selectedBarangay}</span>.
              </p>
              <div className="grid grid-cols-2 gap-3 pt-2">
                <button 
                  onClick={clearCurrent}
                  className="flex items-center justify-center gap-2 py-3 bg-white/10 hover:bg-white/20 rounded-xl text-xs font-bold transition-all"
                >
                  <RotateCcw className="w-3.5 h-3.5" /> Reset
                </button>
                <button 
                  onClick={loadExisting}
                  className="flex items-center justify-center gap-2 py-3 bg-white/10 hover:bg-white/20 rounded-xl text-xs font-bold transition-all"
                >
                  <Layers className="w-3.5 h-3.5" /> Existing
                </button>
              </div>
            </div>

            <button 
              onClick={handleAIGenerate}
              disabled={generatingAI || !selectedBarangay}
              className="w-full flex items-center justify-center gap-3 py-4 bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white rounded-2xl font-black text-sm shadow-xl shadow-emerald-600/20 transition-all active:scale-[0.98]"
            >
              {generatingAI ? (
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
              ) : (
                <Sparkles className="w-5 h-5" />
              )}
              {generatingAI ? 'AI Generating...' : 'Gemini AI Auto-Generate'}
            </button>

            <button 
              onClick={handleSave}
              disabled={saving || points.length < 3}
              className="w-full flex items-center justify-center gap-3 py-4 bg-slate-900 hover:bg-slate-800 disabled:opacity-50 text-white rounded-2xl font-black text-sm shadow-xl shadow-slate-900/20 transition-all active:scale-[0.98]"
            >
              {saving ? <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" /> : <Save className="w-5 h-5" />}
              Save Jurisdiction
            </button>
          </div>
        )}
      </div>

      {/* Map View */}
      <div className="flex-1 relative bg-slate-100">
        <MapContainer center={CEBU_CENTER} zoom={14} className="w-full h-full" zoomControl={false}>
          <MapController center={mapCenter} />
          {isSatellite ? (
            <TileLayer url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" />
          ) : (
            <TileLayer url="https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}" />
          )}

          <MapEvents onMapClick={handleMapClick} />

          {/* Current drawing polygon */}
          {points.length > 0 && (
            <Polygon 
              positions={points}
              pathOptions={{ 
                color: '#10B981', 
                fillColor: '#10B981', 
                fillOpacity: 0.3,
                weight: 3,
                dashArray: '5, 10'
              }}
            />
          )}

          {/* Vertex Markers */}
          {points.map((p, i) => (
            <Marker 
              key={i} 
              position={p}
              icon={L.divIcon({
                html: `<div class="w-3 h-3 bg-emerald-500 border-2 border-white rounded-full shadow-lg"></div>`,
                className: '',
                iconSize: [12, 12],
                iconAnchor: [6, 6]
              })}
            />
          ))}

          {/* Other saved boundaries */}
          {Object.entries(savedBoundaries).map(([brgy, boundary]) => (
            brgy !== selectedBarangay && (
              <Polygon 
                key={brgy}
                positions={boundary}
                pathOptions={{ 
                  color: '#64748b', 
                  fillColor: '#64748b', 
                  fillOpacity: 0.05,
                  weight: 1
                }}
              />
            )
          ))}
        </MapContainer>

        {/* Address Search Bar */}
        <div className="absolute top-6 left-[20px] z-[1000] w-80">
          <div className="relative group">
            <div className="absolute inset-y-0 left-4 flex items-center pointer-events-none">
              {searchLoading ? (
                <div className="w-4 h-4 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin" />
              ) : (
                <Search className="w-4 h-4 text-slate-400" />
              )}
            </div>
            <input
              type="text"
              className="w-full bg-white/90 backdrop-blur-md border border-slate-200 rounded-2xl pl-11 pr-4 py-3.5 text-sm font-bold shadow-2xl focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:bg-white transition-all text-slate-700"
              placeholder="Find address or landmark..."
              value={searchQuery}
              onChange={(e) => handleSearch(e.target.value)}
            />
            
            {searchResults.length > 0 && (
              <div className="absolute top-full left-0 right-0 mt-3 bg-white rounded-3xl shadow-2xl border border-slate-100 overflow-hidden animate-in fade-in slide-in-from-top-2 duration-200">
                {searchResults.map((res, i) => (
                  <button
                    key={i}
                    onClick={() => selectSearchResult(res)}
                    className="w-full px-5 py-4 text-left text-xs font-bold text-slate-700 hover:bg-emerald-50 border-b border-slate-50 last:border-0 transition-colors flex items-start gap-3"
                  >
                    <MapPin className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                    <span className="truncate">{res.display_name}</span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Map Overlays */}
        <div className="absolute top-6 right-6 z-[1000] flex flex-col gap-3">
          <button
            onClick={() => setIsSatellite(!isSatellite)}
            className={`flex items-center gap-3 px-5 py-3 rounded-2xl text-xs font-black transition-all shadow-2xl backdrop-blur-md border ${
              isSatellite ? 'bg-emerald-600 text-white border-emerald-500' : 'bg-white text-slate-700 border-slate-200'
            }`}
          >
            <MapIcon className="w-4 h-4" /> {isSatellite ? 'Satellite' : 'Standard'}
          </button>
        </div>

        {/* Hint */}
        {!selectedBarangay && (
          <div className="absolute inset-0 z-[1001] bg-slate-900/5 backdrop-blur-[2px] flex items-center justify-center pointer-events-none">
            <div className="bg-white/90 px-8 py-6 rounded-[32px] shadow-2xl border border-white flex items-center gap-4 animate-in zoom-in-95 duration-500">
              <div className="w-12 h-12 bg-emerald-100 rounded-2xl flex items-center justify-center text-emerald-600">
                <MapIcon className="w-6 h-6" />
              </div>
              <div>
                <p className="text-base font-black text-slate-900">Select a Barangay</p>
                <p className="text-xs text-slate-500 font-bold uppercase tracking-widest">To begin drawing jurisdiction</p>
              </div>
            </div>
          </div>
        )}

        {/* Toast */}
        {toast && (
          <div className={`absolute bottom-8 left-1/2 -translate-x-1/2 z-[1000] px-6 py-4 rounded-3xl shadow-2xl flex items-center gap-3 animate-in slide-in-from-bottom-4 ${
            toast.type === 'success' ? 'bg-emerald-600 text-white' : 'bg-slate-900 text-white'
          }`}>
            {toast.type === 'success' ? <CheckCircle className="w-5 h-5" /> : <AlertCircle className="w-5 h-5" />}
            <span className="text-sm font-bold">{toast.msg}</span>
          </div>
        )}
      </div>
    </div>
  );
}
