module.exports = {
  Truck: require("./Truck.js"),
  Report: require("./Report.js"),
  Fleet: require("./Fleet.js"),
  Route: require("./Route.js"),
  Schedule: require("./Schedule.js"),
  Sitio: require("./Sitio.js"),
  GarbageArea: require("./GarbageArea.js"),
  CollectionLog: require("./CollectionLog.js"),
  SensorReading: require("./SensorReading.js"),
  IoTAlert: require("./IoTAlert.js"),
  Official: require("./Official.js"),
  ErrorLog: require("./ErrorLog.js"),
  BugReport: require("./BugReport.js"),
  Resident: require("./Resident.js"),
  User: require("./User.js"),
  DisposalVerification: require("./DisposalVerification.js"),
  Reward: require("./Reward.js"),
  BarangayBoundary: require("./BarangayBoundary.js"),
  BarangayScore: require("./BarangayScore.js"),
  BarangayPointHistory: require("./BarangayPointHistory.js"),
  Announcement: require("./Announcement.js"),
  PickupRun: require("./PickupRun.js"),
  BinStatus: require("./BinStatus.js"),
  CleanupPost: require("./CleanupPost.js"),
  SurveyResponse: require("./SurveyResponse.js"),
};
